<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <relativePath>../../pom.xml</relativePath>
        <artifactId>airsonic</artifactId>
        <version>13.2.0</version>
        <groupId>org.airsonic.player</groupId>
    </parent>
    <packaging>pom</packaging>
    <artifactId>airsonic-docker</artifactId>
    <name>Airsonic-Pulse Docker Image</name>

    <dependencies>
        <dependency>
            <groupId>org.airsonic.player</groupId>
            <artifactId>airsonic-main</artifactId>
            <version>13.2.0</version>
            <type>war</type>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.10.0</version>
                <groupId>org.apache.maven.plugins</groupId>
                <configuration>
                    <stripClassifier>true</stripClassifier>
                    <stripVersion>true</stripVersion>
                </configuration>
                <executions>
                    <execution>
                        <id>copy</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
